image: java

pipelines:
  branches:
    mvp1rc:
      - step:
          script:
            - git submodule update --init --recursive
            - apt-get update && apt-get install -y maven python python-pip
            - pip install --upgrade pip
            - pip install -r bitbucket-python-pipeline-requirements.txt
            - make build-base
            - make atdd
            #- git fetch
            #- git checkout -b rc
            #- git push -v --tags origin rc:rc
    rc:
      - step:
          script:
            - make build-base
            - git fetch
            - git checkout -b master
            - git merge rc
            - git push -v --tags origin master:master       
    master:
      - step:
          script:
            - echo "this is the master branch"

options:
  docker: true