image: python:3.5.1

pipelines:
  branches:
    mvp1rc:
      - step:
          script:
            - echo "deb http://http.debian.net/debian jessie-backports main" >> /etc/apt/sources.list
            - apt-get update && apt-get install -y maven openjdk-8-jdk
            - export JAVA_VER=8
            - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
            - pip install -r bitbucket-python-pipeline-requirements.txt
            - pip install docker-compose
            - make build-base
            - make atdd
            #- git fetch
            #- git checkout -b rc
            #- git push -v --tags origin rc:rc
    rc:
      - step:
          script:
            - make build-base
            - git fetch
            - git checkout -b master
            - git merge rc
            - git push -v --tags origin master:master       
    master:
      - step:
          script:
            - echo "this is the master branch"

options:
  docker: true