version: '2'
services:

  hello-world:
    build: services/hello-world/
    image: kilda/hello-world:${BUILD_NUMBER:-latest}
    command: /app/helloworld.sh
    env_file:
      - services/hello-world/variables.env
  
  mininet:
    build: services/mininet/
    image: kilda/mininet:${BUILD_NUMBER:-latest}
    command: mn
    env_file:
      - services/mininet/variables.env

  openflow-speaker:
    build: services/openflow-speaker/
    image: kilda/openflow-speaker:${BUILD_NUMBER:-latest}
    command: /app/app.sh
    ports:
      - "6633:6633"

  neo4j:
    build: services/neo4j/
    image: kilda/neo4j:${BUILD_NUMBER:-latest}
    command: neo4j console
    ports:
      - "7474:7474"
      - "7687:7687"

  topology-engine:
    build: services/topology-engine/
    image: kilda/topology-engine:${BUILD_NUMBER:-latest}
    command: python app/helloworld.py
    ports:
      - "80:80"
    links:
      - neo4j

  zookeeper:
    build: services/zookeeper/
    image: kilda/zookeeper:${BUILD_NUMBER:-latest}
    command: /opt/zookeeper/bin/zkServer.sh start-foreground
    volumes:
      - zookeeper_data:/data/zookeeper
    ports:
      - "2181:2181"

  kafka:
    build: services/kafka/
    image: kilda/kafka:${BUILD_NUMBER:-latest}
    command: /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
    volumes:
      - kafka_data:/data/kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper.pendev
    ports:
      - "9092:9092"

  hbase:
    build: services/hbase
    image: kilda/hbase:${BUILD_NUMBER:-latest}
    command: /opt/hbase/bin/start-hbase
    volumes:
      - hbase_data:/data/hbase
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper.pendev
    ports:
      - "60000:60000"
      - "60010:60010"
      - "60020:60020"
      - "60030:60030"
      - "8070:8070"
      - "8090:8090"
      - "9070:9070"
      - "9090:9090"

  opentsdb:
    build: services/opentsdb
    image: kilda/opentsdb:${BUILD_NUMBER:-latest}
    command: /app/wait-for-it.sh -t 120 -h hbase.pendev -p 9090 -- /app/start-opentsdb
    environment:
      - JAVA_HOME=/usr
      - HBASE_HOME=/opt/hbase
      - COMPRESSION=NONE
    depends_on:
      - zookeeper
      - hbase
    links:
      - zookeeper:zookeeper.pendev
      - hbase:hbase.pendev
    ports:
      - "4242:4242"

  tools:
    build: services/tools
    image: kilda/tools:${BUILD_NUMBER:-latest}
    command: sleep 10d
    depends_on:
      - zookeeper
      - hbase
      - storm_nimbus
      - storm_supervisor
    links:
      - zookeeper:zookeeper.pendev
      - hbase:hbase.pendev
      - storm_nimbus:nimbus.pendev
      - storm_supervisor:supervisor.pendev
    ports:
      - "22:8022"
    container_name: "hadoop-tools"

  storm_nimbus:
    build: services/storm
    image: kilda/storm:${BUILD_NUMBER:-latest}
    command: /app/wait-for-it.sh -t 120 -h zookeeper.pendev -p 2181 -- /opt/storm/bin/storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper.pendev
      - hbase:hbase.pendev
    ports:
      - "6627:6627"
      - "3772:3772"
      - "3773:3773"

  storm_ui:
    build: services/storm
    image: kilda/storm:${BUILD_NUMBER:-latest}
    command: /app/wait-for-it.sh -t 120 -h zookeeper.pendev -p 2181 -- /opt/storm/bin/storm ui
    depends_on:
      - zookeeper
      - storm_nimbus
      - storm_supervisor
    links:
      - zookeeper:zookeeper.pendev
      - hbase:hbase.pendev
      - storm_nimbus:nimbus.pendev
      - storm_supervisor:supervisor.pendev
    ports:
      - "8080:8080"

  storm_supervisor:
    build: services/storm
    image: kilda/storm:${BUILD_NUMBER:-latest}
    command: /app/wait-for-it.sh -t 120 -h zookeeper.pendev -p 2181 -- /opt/storm/bin/storm supervisor
    depends_on:
      - zookeeper
      - storm_nimbus
    links:
      - zookeeper:zookeeper.pendev
      - hbase:hbase.pendev
      - storm_nimbus:nimbus.pendev
    ports:
      - "6700:6700"
      - "6701:6701"
      - "6702:6702"
      - "6703:6703"
      - "8000:8000"

  floodlight:
    build: services/floodlight
    image: kilda/floodlight:${BUILD_NUMBER:-latest}
    command: java -jar /app/floodlight/target/floodlight.jar -cf /app/floodlight/src/main/resources/floodlightdefault.properties
    ports:
      - "6653:6653"
      - "8180:8080"
      - "6655:6655"
      - "6642:6642"

volumes:
  hbase_data:
  zookeeper_data:
  kafka_data:
