version: '2'
services:

  hello-world:
    build: services/hello-world/
    image: kilda/hello-world:latest
    command: /app/helloworld.sh

  openflow-speaker:
    build: services/openflow-speaker/
    image: kilda/openflow-speaker:latest
    #command: /app/runner.sh
    ports:
      - "6633:6633"

  neo4j:
    build: services/neo4j/
    image: kilda/neo4j:latest
    command: neo4j console
    ports:
      - "7474:7474"

  zookeeper:
    build: services/zookeeper/
    image: kilda/zookeeper:latest
    command: /opt/zookeeper/bin/zkServer.sh start-foreground
    ports:
      - "2181:2181"

  kafka:
    build: services/kafka/
    image: kilda/kafka:latest
    command: /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper.pendev
    ports:
      - "9092:9092"

  hbase:
    build: services/hbase
    image: kilda/hbase:latest
    command: /opt/hbase/bin/start-hbase
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper.pendev
    ports:
      - "60000:60000"
      - "60010:60010"
      - "60020:60020"
      - "60030:60030"
      - "8070:8070"
      - "8090:8090"

  opentsdb:
    build: services/opentsdb
    image: kilda/opentsdb:latest
    command: sleep 1d
    environment:
      - JAVA_HOME=/usr
      - HBASE_HOME=/opt/hbase
      - COMPRESSION=NONE
    depends_on:
      - zookeeper
      - hbase
    links:
      - zookeeper:zookeeper.pendev
      - hbase:hbase.pendev
    ports:
      - "4242:4242"

  tools:
    build: services/tools
    image: kilda/tools:latest
    command: sleep 10d
    depends_on:
      - zookeeper
      - hbase
    links:
      - zookeeper:zookeeper.pendev
      - hbase:hbase.pendev
    ports:
      - "22:8022"
    container_name: "hadoop-tools"
