version: '2'
services:

  hello-world:
    build: services/hello-world/
    image: kilda/hello-world:latest
    command: /app/helloworld.sh

  openflow-speaker:
    build: services/openflow-speaker/
    image: kilda/openflow-speaker:latest 
    #command: /app/runner.sh
    ports:
    - "6633:6633" 

  neo4j:
    build: services/neo4j/
    image: kilda/neo4j:latest
    command: neo4j console
    ports:
    - "7474:7474"