---
- hosts: localhost
  tasks:

  - name: get opentsdb
    get_url:
      url="https://github.com/OpenTSDB/opentsdb/releases/download/v2.3.0/opentsdb-2.3.0_all.deb"
      dest="/tmp/opentsdb-2.3.0.deb"

  - name: install apt packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - gnuplot
      - python-happybase
    become_method: sudo
    become_user: root
    become: true

  - name: install opentsdb
    apt: deb="/tmp/opentsdb-2.3.0.deb"
    become_method: sudo
    become_user: root
    become: true
