---
- hosts: localhost
  tasks:
  - name: install apt packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
    - git
    - ant
    - maven
    become_method: sudo
    become_user: root
    become: true

  - name: git loxigen
    git:
       repo=https://github.com/floodlight/loxigen.git
       dest=/app/loxigen
       clone=yes
       recursive=yes
  - name: build loxigen
    shell: "{{ item }}"
    with_items:
    - /bin/bash /app/build_loxigen.sh

  - name: git floodlight
    git: 
       repo=https://github.com/kilda/floodlight.git
       dest=/app/floodlight
       clone=yes
       recursive=yes
  - name: build floodlight
    shell: "{{ item }}"
    with_items:
    - /bin/bash /app/build_floodlight.sh

