---
- hosts: localhost
  tasks:
  - name: install apt packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
    - git
    - ant
    - maven
    become_method: sudo
    become_user: root
    become: true

  - name: git loxigen
    git:
       repo=https://github.com/floodlight/loxigen.git
       dest=/app/loxigen
       clone=yes
       recursive=yes
  - name: build loxigen
    shell: "{{ item }}"
    with_items:
    - /bin/bash /app/build_loxigen.sh

  - name: check jar was installed
    stat:
      path: /root/.m2/repository/org/projectfloodlight/openflowj/3.2.0-SNAPSHOT/openflowj-3.2.0-SNAPSHOT.jar
    register: stat_result

  - name: git floodlight
    git: 
       repo=https://github.com/kilda/floodlight.git
       dest=/app/floodlight
       clone=yes
       recursive=yes
  - name: build floodlight
    shell: "{{ item }}"
    with_items:
    - /bin/bash /app/build_floodlight.sh

  - name: check jar was installed
    stat:
      path: /root/.m2/repository/org/projectfloodlight/floodlight/1.2-SNAPSHOT/floodlight-1.2-SNAPSHOT.jar 
    register: stat_result

