---
- hosts: localhost
  tasks:
  - name: add neo4j apt repo
    shell: "{{ item }}"
    with_items:
    - wget -O - https://debian.neo4j.org/neotechnology.gpg.key | apt-key add -
    - echo 'deb http://debian.neo4j.org/repo stable/' | tee /etc/apt/sources.list.d/neo4j.list
    
  - name: install apt packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
    - neo4j
    - curl
    become_method: sudo
    become_user: root
    become: true
