---
- hosts: localhost
  tasks:
  - name: check linux version
    shell: uname -r
    ignore_errors: yes
    register: uname_result

  - name: install apt packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
    - mininet
    - net-tools
    - inetutils-ping
    - autoconf
    - automake
    - ca-certificates
    - git
    - libtool
    - openssh-client
    - patch
    - vim
    - python-bottle
    - python-jsonschema
    - python-scapy
    become_method: sudo
    become_user: root
    become: true

  - name: add xenial repo
    apt_repository:
      repo: deb http://security.ubuntu.com/ubuntu xenial-security main
      state: present
  - name: install linux image with modules.dep.bin
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
    - linux-image-{{ uname_result.stdout }}
    become_method: sudo
    become_user: root
    become: true

