---
- hosts: localhost

  vars_files:
    - sources.yml

  tasks:

  - name: create opt dir
    file: path=/opt state=directory

  - name: get storm
    unarchive:
      src={{ default_url }}/storm/apache-storm-1.0.2/apache-storm-1.0.2.tar.gz
      dest=/opt
      remote_src=yes
      owner=root
      group=root

  - name: create storm link
    file: src=/opt/apache-storm-1.0.2 dest=/opt/storm state=link owner=root group=root
