---
- hosts: localhost
  tasks:
  - name: install apt packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
    - python-pip
    become_method: sudo
    become_user: root
    become: true
