---
- hosts: localhost
  tasks:

  - name: create opt dir
    file: path=/opt state=directory

  - name: get hbase
    unarchive: 
      src=http://ftp.kddilabs.jp/infosystems/apache/hbase/1.2.3/hbase-1.2.3-bin.tar.gz
      dest=/opt 
      remote_src=yes 
      owner=root
      group=root

  - name: create hbase link
    file: src=/opt/hbase-1.2.3 dest=/opt/hbase state=link owner=root group=root

  - name: install apt packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
    - net-tools
    - default-jre
    become_method: sudo
    become_user: root
    become: true
