---
- hosts: localhost
  tasks:
  - name: install apt packages
    shell: "{{ item }}"
    with items:
    - apt-get clean
    - apt-get update

    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
    - vim
    become_method: sudo
    become_user: root
    become: true
